=== harawata/ibatis-apache-svn/java/mapper/mapper2/src/com/ibatis/sqlmap/engine/builder/xml/sql-map-2.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT sqlMap (typeAlias* | cacheModel* | resultMap* | parameterMap* | statement* | insert* | update* | delete* | select* | procedure*)+>
<!ATTLIST sqlMap
xmlns:fo CDATA #IMPLIED
namespace CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)>
<!ATTLIST parameterMap
id CDATA #REQUIRED
class CDATA #REQUIRED
>
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
nullValue CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
>
<!ELEMENT resultMap (result+)>
<!ATTLIST resultMap
id CDATA #REQUIRED
class CDATA #REQUIRED
extends CDATA #IMPLIED
xmlName CDATA #IMPLIED
>
<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #REQUIRED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
columnIndex CDATA #IMPLIED
jdbcType CDATA #IMPLIED
nullValue CDATA #IMPLIED
select CDATA #IMPLIED
>
<!ELEMENT cacheModel (flushInterval?, flushOnExecute*, property*)+>
<!ATTLIST cacheModel
id CDATA #REQUIRED
type CDATA #REQUIRED
readOnly (true | false) #IMPLIED
serialize (true | false) #IMPLIED
>
<!ELEMENT flushInterval EMPTY>
<!ATTLIST flushInterval
milliseconds CDATA #IMPLIED
seconds CDATA #IMPLIED
minutes CDATA #IMPLIED
hours CDATA #IMPLIED
>
<!ELEMENT flushOnExecute EMPTY>
<!ATTLIST flushOnExecute
statement CDATA #REQUIRED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT statement (#PCDATA | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST statement
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultClass CDATA #IMPLIED
cacheModel CDATA #IMPLIED
xmlResultName CDATA #IMPLIED
>

<!ELEMENT select (#PCDATA | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultClass CDATA #IMPLIED
cacheModel CDATA #IMPLIED
xmlResultName CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA | selectKey | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA) >
<!ATTLIST selectKey
resultClass CDATA #IMPLIED
keyProperty CDATA #IMPLIED
>

<!ELEMENT update (#PCDATA | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
>

<!ELEMENT procedure (#PCDATA | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST procedure
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultClass CDATA #IMPLIED
cacheModel CDATA #IMPLIED
xmlResultName CDATA #IMPLIED
>

<!-- - - - - - - - - - - - - - - - - - - - - - - - -
                 DYNAMIC ELEMENTS
  - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT dynamic (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST dynamic
prepend CDATA #IMPLIED
>

<!ELEMENT isNotNull (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotNull
prepend CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT isNull (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNull
prepend CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT isNotPropertyAvailable (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotPropertyAvailable
prepend CDATA #IMPLIED
property CDATA #REQUIRED
>

<!ELEMENT isPropertyAvailable (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isPropertyAvailable
prepend CDATA #IMPLIED
property CDATA #REQUIRED
>

<!ELEMENT isEqual (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isEqual
prepend CDATA #IMPLIED
property CDATA #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isNotEqual (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotEqual
prepend CDATA #IMPLIED
property CDATA #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isGreaterThan (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isGreaterThan
prepend CDATA #IMPLIED
property CDATA #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isGreaterEqual (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isGreaterEqual
prepend CDATA #IMPLIED
property CDATA #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isLessThan (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isLessThan
prepend CDATA #IMPLIED
property CDATA #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isLessEqual (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isLessEqual
prepend CDATA #IMPLIED
property CDATA #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isEmpty (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isEmpty
prepend CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT isNotEmpty (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotEmpty
prepend CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT isParameterPresent (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isParameterPresent
prepend CDATA #IMPLIED
>

<!ELEMENT isNotParameterPresent (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotParameterPresent
prepend CDATA #IMPLIED
>

<!ELEMENT iterate (#PCDATA | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST iterate
prepend CDATA #IMPLIED
property CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
conjunction CDATA #IMPLIED
>

=== harawata/ibatis-apache-svn/java/mapper/mapper2/javadoc/com/ibatis/sqlmap/client/sql-map.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sqlMap
    PUBLIC "-//iBATIS.com//DTD SQL Map Config 2.0//EN"
    "http://www.ibatis.com/dtd/sql-map-2.dtd">

<!-- Be sure to always use the appropriate header as above!  Note the 2.0 DTDs. -->

<sqlMap>

  <!-- A type alias can be used to declare a shorter name for a long fully qualified
       classname.  There can be any number of typeAlias elements.  -->

  <typeAlias alias="shortname2" type="com.long.class.path.Class2"/>

  <!-- A cacheModel stanza is used to configure a cache.  In this case a cache
       named accountCache will be created using least recently used semantics (LRU).
       The cache has been flagged as readOnly indicating that objects retrieved
       from the cache might be modified.  This cache will be flushed every
       24 hours and when one of the identified statements is executed.
       Finally, the LRU cache takes only one optional property, which is the
       size (in this case 100).  There can be any number of cacheModel
       stanzas. Of course, cache models are optional. -->

  <cacheModel id="accountCache" type="LRU" readOnly="true" >
    <flushInterval hours="24"/>
    <flushOnExecute statement="insertAccount"/>
    <flushOnExecute statement="updateAccount"/>
    <flushOnExecute statement="deleteAccount"/>
    <property name="cacheSize" value="100"/>
  </cacheModel>

  <!-- The resultMap stanza is used to map the result set to the result object.
       A result object could be many things, including JavaBean, a Map, a primitive
       type wrapper, or even an XML document. Result maps are referred to by their
       id attribute by mapped statements (see below).  The result map contains
       any number of result elements, each of which maps a single column to
       a property.  The property might be a JavaBean property, a map key, or
       an XML element.  In the case of a primitive type wrapper (e.g. Integer or
       String), there can be only one result, with any property name. -->

  <resultMap id="myResultMap" class="domain.MyClass">
    <result property="id" column="MY_ID" />
    <result property="name" column="MY_NAME" />
    <result property="city" column="MY_CITY" />
    <!--
    <result property="" column="" columnIndex="" jdbcType="" javaType="" nullValue="" select=""/>
    -->
  </resultMap>

  <!-- The parameterMap stanza maps a parameter object to the input parameters of a
       PreparedStatement (question marks "?").  A parameter object could be many things,
       including JavaBean, a Map, a primitive type wrapper, or even an XML document.
       Parameter maps are referred to by their id attribute by mapped statements
       (see below).  The parameter map contains any number of parameter elements,
       each of which maps a property to a single statement parameter.  The property
       might be a JavaBean property, a map key, or an XML element.  In the case of a
       primitive type wrapper (e.g. Integer or String), there can be only one result,
       with any property name.  In the case of a prepared statement, the parameter
       might be an output parameter, which are fully supported.  There can be any
       number of parameterMap stanzas.

       IMPORTANT: Using the parameterMap stanza is usually more verbose than necessary,
       and for that reason statements can use inline parameter maps (using #property#
       tokens) within the SQL statement itself.  This makes the SQL easier to read.
       See below for more.

       NOTE: Most of the attributes are OPTIONAL, but are included here for completeness. -->

  <parameterMap id="myParameterMap" class="domain.MyClass">
    <parameter property="id"   mode="IN" />
    <parameter property="name" mode="OUT" />
    <parameter property="city" mode="INOUT" />
    <!--
    <parameter property="" jdbcType="" javaType="" nullValue="" mode="IN" />
    -->
  </parameterMap>

  <!-- The remainder of this example document shows the various SQL statement
       stanzas that can be used to describe your mapped statements.  These statements
       can be complete SQL statements and can include aggregations, concatenations,
       sub-selects functions and anything else SQL can do.  They can also include
       inline parameters (e.g. #property#) and also dynamic elements for building
       different SQL statements based on the state of the parameter object.
       There can be any number of statement stanzas -->

  <!-- Notice the inline parameter maps in use by the insert statement below.
       Insert statements also have a special selectKey element in their structure
       that allows auto-generated keys to be easily retrieved. -->

  <insert id="myInsert" parameterMap="domain.MyClass">
    insert into MY_TABLE (MY_ID, MY_NAME, MY_CITY) values (#id#, #name#, #city#)
    <selectKey resultClass="int" keyProperty="id" >
      select @@IDENTITY;
    </selectKey>
  </insert>

  <update id="myUpdate" parameterClass="domain.MyClass">
    update MY_TABLE set MY_NAME = "name" where MY_ID = #id#
  </update>

  <delete id="myDelete" parameterClass="domain.MyClass">
    delete from MY_TABLE where MY_ID = #id#
  </delete>

  <select id="mySelect" parameterClass="int" resultMap="myResultMap" cacheModel="myCacheModel">
    select
      MY_ID,
      MY_NAME,
      MY_CITY
    from
      MY_TABLE
    where MY_ID = #id#
  </select>

  <!-- This procedure statement uses a parameter map that defines its output parameters
       that will be set on the parameter object after successful execution.  -->

  <procedure id="myProcedure" resultMap="myResultMap" parameterMap="myParamMap">
    {call myproc(?,?,?)}
  </procedure>

  <!-- The statement stanza is a catch-all that allows any kind of statement
       to be run.  -->

  <statement id="myStatement" >
     update MY_TABLE set MY_ID = 9999999 where MY_ID is null
  </statement>

</sqlMap>

=== harawata/ibatis-apache-svn/java/mapper/mapper2/test/com/ibatis/sqlmap/maps/RepeatingGroupMapping.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE sqlMap SYSTEM "http://www.ibatis.com/dtd/sql-map-2.dtd">

<sqlMap>

  <resultMap id="categoryResult" class="testdomain.Category" groupBy="categoryId">
    <result property="categoryId" column="catid"/>
    <result property="name" column="name"/>
    <result property="description" column="descn"/>
    <!--
    <result property="productList" resultMap="productResult"/>
    -->
  </resultMap>

  <resultMap id="productResult" class="testdomain.Product" groupBy="productId">
    <result property="productId" column="productid"/>
    <result property="categoryId" column="category"/>
    <result property="name" column="name"/>
    <result property="description" column="descn"/>
    <result property="itemList" resultMap="itemResult"/>
  </resultMap>

  <resultMap id="itemResult" class="testdomain.Item">
    <result property="itemId" column="itemid"/>
    <result property="productId" column="productid"/>
    <result property="listPrice" column="listprice"/>
    <result property="unitCost" column="unitcost"/>
    <result property="supplierId" column="supplier"/>
    <result property="status" column="status"/>
    <result property="attribute1" column="attr1"/>
    <result property="quantity" column="qty"/>
  </resultMap>

  <select id="getAllCategories" resultMap="categoryResult" >
    select *
    from category c, product p, item i
    where c.catid = p.category
      and p.productid = i.productid
  </select>

</sqlMap>

=== harawata/ibatis-apache-svn/java/mapper/mapper2/test/com/ibatis/sqlmap/maps/OracleProc.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE sqlMap
    PUBLIC "-//iBATIS.com//DTD SQL Map 2.0//EN"
    "http://www.ibatis.com/dtd/sql-map-2.dtd">

<sqlMap>

  <parameterMap id="swapParameters" class="map" >
    <parameter property="email1" jdbcType="VARCHAR" javaType="java.lang.String" mode="INOUT"/>
    <parameter property="email2" jdbcType="VARCHAR" javaType="java.lang.String" mode="INOUT"/>
    <parameter property="status" jdbcType="VARCHAR" javaType="java.lang.String" mode="OUT"/>
  </parameterMap>

  <procedure id="swapEmailAddresses" parameterMap="swapParameters" >
     {call swap_email_address (?, ?, ?)}
  </procedure>

  <parameterMap id="swapParametersUsingBean" class="testdomain.ProcBean" >
    <parameter property="email1" jdbcType="VARCHAR" javaType="java.lang.String" mode="INOUT"/>
    <parameter property="email2" jdbcType="VARCHAR" javaType="java.lang.String" mode="INOUT"/>
    <parameter property="status" jdbcType="VARCHAR" javaType="java.lang.String" mode="OUT"/>
  </parameterMap>

  <procedure id="swapEmailAddressesUsingBean" parameterMap="swapParametersUsingBean" >
     {call swap_email_address (?, ?, ?)}
  </procedure>

  <procedure id="noParamProc" resultClass="string">
     {call no_param_proc ()}
  </procedure>

</sqlMap>

=== harawata/ibatis-apache-svn/java/mapper/mapper2/test/com/ibatis/sqlmap/maps/DerbyProc.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE sqlMap      
    PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN"      
    "http://ibatis.apache.org/dtd/sql-map-2.dtd">

<sqlMap namespace="DerbyProc">

  <typeAlias alias="account" type="testdomain.Account"/>

  <parameterMap id="multiList" class="map" >
    <parameter property="accountId1" jdbcType="INTEGER" javaType="java.lang.Integer" mode="IN"/>
    <parameter property="accountId2" jdbcType="INTEGER" javaType="java.lang.Integer" mode="IN"/>
    <parameter property="accountId3" jdbcType="INTEGER" javaType="java.lang.Integer" mode="IN"/>
    <parameter property="accountId4" jdbcType="INTEGER" javaType="java.lang.Integer" mode="IN"/>
  </parameterMap>
  
  <resultMap id="account-result" class="account">
    <result property="id" column="ACC_ID" columnIndex="1"/>
    <result property="firstName" column="ACC_FIRST_NAME" columnIndex="2"/>
    <result property="lastName" column="ACC_LAST_NAME" columnIndex="3"/>
    <result property="emailAddress" column="ACC_EMAIL" columnIndex="4" nullValue="no_email@provided.com"/>
  </resultMap>
  <!-- <parameter property="accountList" javaType="list" mode="OUT"/> -->
  <!-- <parameter property="accountList" javaType="list" mode="OUT"/> -->
  
  <procedure id="getMultiListsRm" parameterMap="multiList" resultMap="account-result">
     {call MRESULTSET(?,?,?,?)}
  </procedure>
  
  <procedure id="getMultiListsRc" parameterMap="multiList" resultClass="account">
     {call MRESULTSET(?,?,?,?)}
  </procedure>
</sqlMap>
