=== harawata/ibatis-apache-svn/java/mapper/mapper2/src/com/ibatis/sqlmap/engine/builder/xml/sql-map-config-2.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT sqlMapConfig (properties?, settings?, typeAlias*, transactionManager?, sqlMap+)+>
<!ATTLIST sqlMapConfig
	xmlns:fo CDATA #IMPLIED
>

<!ELEMENT properties EMPTY>
<!ATTLIST properties
	resource CDATA #IMPLIED
	url CDATA #IMPLIED
>

<!ELEMENT settings EMPTY>
<!ATTLIST settings
  lazyLoadingEnabled (true | false) #IMPLIED
  cacheModelsEnabled (true | false) #IMPLIED
  enhancementEnabled (true | false) #IMPLIED
  errorTracingEnabled (true | false) #IMPLIED
  useStatementNamespaces (true | false) #IMPLIED
  maxSessions CDATA #IMPLIED
  maxTransactions CDATA #IMPLIED
  maxRequests CDATA #IMPLIED
>

<!ELEMENT transactionManager (property*,dataSource)>
<!ATTLIST transactionManager
	type (JDBC | JTA | EXTERNAL) #REQUIRED
>

<!ELEMENT dataSource (property*)>
<!ATTLIST dataSource
	type (SIMPLE | DBCP | JNDI) #REQUIRED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT sqlMap EMPTY>
<!ATTLIST sqlMap
	resource CDATA #IMPLIED
	url CDATA #IMPLIED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
	alias CDATA #REQUIRED
	type CDATA #REQUIRED
>

=== harawata/ibatis-apache-svn/java/mapper/mapper2/test/com/ibatis/sqlmap/maps/SqlMapConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sqlMapConfig
    PUBLIC "-//iBATIS.com//DTD SQL Map Config 2.0//EN"
    "http://www.ibatis.com/dtd/sql-map-config-2.dtd">

<sqlMapConfig>

  <properties resource="com/ibatis/sqlmap/maps/SqlMapConfig.properties"/>

  <!-- settings
	add these to test bug 976614
	enhancementEnabled="false"
    lazyLoadingEnabled="false"
  -->

  <settings
    cacheModelsEnabled="true"
    enhancementEnabled="true"
    lazyLoadingEnabled="true"
    errorTracingEnabled="false"
    maxRequests="32"
    maxSessions="10"
    maxTransactions="5"
    useStatementNamespaces="false"
    />

  <typeAlias alias="order" type="testdomain.Order"/>
  <typeAlias alias="OuiNonBool" type="com.ibatis.sqlmap.extensions.OuiNonTypeHandlerCallback"/>

  <typeHandler javaType="boolean" jdbcType="VARCHAR" callback="OuiNonBool" />

  <transactionManager type="JDBC">
    <dataSource type="SIMPLE">
      <property name="JDBC.Driver" value="${driver}"/>
      <property name="JDBC.ConnectionURL" value="${url}"/>
      <property name="JDBC.Username" value="${username}"/>
      <property name="JDBC.Password" value="${password}"/>
      <property name="JDBC.DefaultAutoCommit" value="true"/>
      <property name="Pool.MaximumActiveConnections" value="10"/>
      <property name="Pool.MaximumIdleConnections" value="5"/>
      <property name="Pool.MaximumCheckoutTime" value="120000"/>
      <property name="Pool.TimeToWait" value="500"/>
      <property name="Pool.PingQuery" value="select 1 from ACCOUNT"/>
      <property name="Pool.PingEnabled" value="false"/>
      <property name="Pool.PingConnectionsOlderThan" value="1"/>
      <property name="Pool.PingConnectionsNotUsedFor" value="1"/>
      <property name="Pool.QuietMode" value="true"/>
    </dataSource>
  </transactionManager>

  <sqlMap resource="com/ibatis/sqlmap/maps/Account.xml"/>
  <sqlMap resource="com/ibatis/sqlmap/maps/DynamicAccount.xml"/>
  <sqlMap resource="com/ibatis/sqlmap/maps/Order.xml"/>
  <sqlMap resource="com/ibatis/sqlmap/maps/LineItem.xml"/>
  <sqlMap resource="com/ibatis/sqlmap/maps/OracleProc.xml"/>
  <sqlMap resource="com/ibatis/sqlmap/maps/Complex.xml"/>
  <sqlMap resource="com/ibatis/sqlmap/maps/XmlStatements.xml"/>
  <sqlMap resource="com/ibatis/sqlmap/maps/DomStatements.xml"/>

</sqlMapConfig>

=== harawata/ibatis-apache-svn/java/tools/ibator/core/testJava5/ibatortest/execute/hierarchical/java5/SqlMapConfig_spring.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMapConfig
  PUBLIC "-//ibatis.apache.org//DTD SQL Map Config 2.0//EN"
  "http://ibatis.apache.org/dtd/sql-map-config-2.dtd">

<sqlMapConfig>

  <settings useStatementNamespaces="true" />

  <sqlMap resource="ibatortest/generated/hierarchical/java5/xml/FIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/hierarchical/java5/xml/FIELDSONLY_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/hierarchical/java5/xml/PKBLOBS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/hierarchical/java5/xml/PKFIELDS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/hierarchical/java5/xml/PKFIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/hierarchical/java5/xml/PKONLY_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/hierarchical/java5/xml/awful table_SqlMap.xml" />

</sqlMapConfig>

=== harawata/ibatis-apache-svn/java/tools/ibator/core/testJava5/ibatortest/execute/conditional/java2/SqlMapConfig_spring.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMapConfig
  PUBLIC "-//ibatis.apache.org//DTD SQL Map Config 2.0//EN"
  "http://ibatis.apache.org/dtd/sql-map-config-2.dtd">

<sqlMapConfig>

  <settings useStatementNamespaces="true" />

  <sqlMap resource="ibatortest/generated/conditional/java2/xml/FIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/conditional/java2/xml/FIELDSONLY_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/conditional/java2/xml/PKBLOBS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/conditional/java2/xml/PKFIELDS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/conditional/java2/xml/PKFIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/conditional/java2/xml/PKONLY_SqlMap.xml" />
  <sqlMap resource="ibatortest/generated/conditional/java2/xml/awful table_SqlMap.xml" />

</sqlMapConfig>

=== harawata/ibatis-apache-svn/java/mapper/mapper2/javadoc/com/ibatis/sqlmap/client/sql-map-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sqlMapConfig
    PUBLIC "-//iBATIS.com//DTD SQL Map Config 2.0//EN"
    "http://www.ibatis.com/dtd/sql-map-config-2.dtd">

<!-- Be sure to always use the appropriate header as above!  Note the 2.0 DTDs. -->

<sqlMapConfig>


  <!-- Using the properties element you can declare an external properties resource
       either from the classpath (resource) or from a URL (e.g. file:// or http://)
       The properties can be referred to throughout the rest of the file using
       the syntax "${propName}". There can be only one properties element. -->

  <properties resource="" url=""/>

  <!-- The settings element has a number of configuration switches and properties
       that configure the SQL Maps engine. Most are performance tweaks or resource
       management.  They are pretty self explanatory. The defaults are shown here.
       There can be only one settins element.  -->

  <settings
    lazyLoadingEnabled="true"
    cacheModelsEnabled="true"
    enhancementEnabled="true"
    maxRequests="512"
    maxSessions="128"
    maxTransactions="32" 
    />

  <!-- A type alias can be used to declare a shorter name for a long fully qualified
       classname.  There can be any number of typeAlias elements.  -->

  <typeAlias alias="shortname" type="com.long.class.path.Class"/>

  <!-- The transaction manager stanza configures a transaction manager such as
       JDBC or JTA.  The following are two examples of transaction managers.
       There can be only ONE defined (uncommented) at a time.  -->

  <!-- This first transaction manager stanza uses JDBC to manage the transactions.
       Within it a dataSource stanza in this case configures SimpleDataSource
       instance that will provide connection pooling services. -->

  <transactionManager type="JDBC">
    <dataSource type="SIMPLE">
      <property name="" value=""/>
      <property name="" value=""/>
      <property name="" value=""/>
    </dataSource>
  </transactionManager>

  <!-- The commented-out transaction manager stanza below uses JTA to manage
       the transactions a global (e.g. distributed) transaction. Within it a
       properties element sets the JNDI path where the JTA UserTransaction
       can be found.  Then, a dataSource stanza is used to configure
       the JNDI lookup for the DataSource from which Connections can be
       opened. -->

  <!--
  <transactionManager type="JTA" >
    <property name="UserTransaction" value="java:/ctx/con"/>
    <dataSource type="JNDI">
      <property name="" value=""/>
      <property name="" value=""/>
      <property name="" value=""/>
    </dataSource>
  </transactionManager>
  -->

  <!-- Finally, the SQL Maps themselves must be registred with the configuration file.
       Below are some examples of some SQL Map reference elements.  Notice that an
       SQL Map can  be located in the classpath (resource) or at a URL (e.g. file://
       or http://).  There can be any number of sqlMap elements. -->

  <sqlMap resource="com.mydomain.sqlmaps.MySqlMap.xml" />
  <!--
  <sqlMap url="file://C:/config/FileSqlMap.xml" />
  <sqlMap url="http://www.ibatis.com/maps/WebSqlMap.xml" />
  -->

</sqlMapConfig>

=== harawata/ibatis-apache-svn/java/mapper/mapper2/tools/abator/core/testJava2/abatortest/java2/execute/hierarchical/legacy/SqlMapConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMapConfig
  PUBLIC "-//ibatis.apache.org//DTD SQL Map Config 2.0//EN"
  "http://ibatis.apache.org/dtd/sql-map-config-2.dtd">

<sqlMapConfig>

  <settings useStatementNamespaces="true" />

  <transactionManager type="JDBC">
    <dataSource type="SIMPLE">
      <property name="JDBC.Driver" value="org.hsqldb.jdbcDriver"/>
      <property name="JDBC.ConnectionURL" value="jdbc:hsqldb:mem:aname"/>
      <property name="JDBC.Username" value="sa"/>
      <property name="JDBC.Password" value=""/>
      <property name="JDBC.DefaultAutoCommit" value="true"/>
    </dataSource>
  </transactionManager>

  <sqlMap resource="abatortest/java2/generated/hierarchical/legacy/xml/FIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="abatortest/java2/generated/hierarchical/legacy/xml/FIELDSONLY_SqlMap.xml" />
  <sqlMap resource="abatortest/java2/generated/hierarchical/legacy/xml/PKBLOBS_SqlMap.xml" />
  <sqlMap resource="abatortest/java2/generated/hierarchical/legacy/xml/PKFIELDS_SqlMap.xml" />
  <sqlMap resource="abatortest/java2/generated/hierarchical/legacy/xml/PKFIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="abatortest/java2/generated/hierarchical/legacy/xml/PKONLY_SqlMap.xml" />
  <sqlMap resource="abatortest/java2/generated/hierarchical/legacy/xml/awful table_SqlMap.xml" />

</sqlMapConfig>

=== harawata/ibatis-apache-svn/java/mapper2/tools/abator/core/testJava5/abatortest/execute/hierarchical/java2/SqlMapConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMapConfig
  PUBLIC "-//ibatis.apache.org//DTD SQL Map Config 2.0//EN"
  "http://ibatis.apache.org/dtd/sql-map-config-2.dtd">

<sqlMapConfig>

  <settings useStatementNamespaces="true" />

  <transactionManager type="JDBC">
    <dataSource type="SIMPLE">
      <property name="JDBC.Driver" value="org.hsqldb.jdbcDriver"/>
      <property name="JDBC.ConnectionURL" value="jdbc:hsqldb:mem:aname"/>
      <property name="JDBC.Username" value="sa"/>
      <property name="JDBC.Password" value=""/>
      <property name="JDBC.DefaultAutoCommit" value="true"/>
    </dataSource>
  </transactionManager>

  <sqlMap resource="abatortest/generated/hierarchical/java2/xml/FIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="abatortest/generated/hierarchical/java2/xml/FIELDSONLY_SqlMap.xml" />
  <sqlMap resource="abatortest/generated/hierarchical/java2/xml/PKBLOBS_SqlMap.xml" />
  <sqlMap resource="abatortest/generated/hierarchical/java2/xml/PKFIELDS_SqlMap.xml" />
  <sqlMap resource="abatortest/generated/hierarchical/java2/xml/PKFIELDSBLOBS_SqlMap.xml" />
  <sqlMap resource="abatortest/generated/hierarchical/java2/xml/PKONLY_SqlMap.xml" />
  <sqlMap resource="abatortest/generated/hierarchical/java2/xml/awful table_SqlMap.xml" />

</sqlMapConfig>
